### ISSUE TITLE
AES-GCM

### ISSUE THREAD

**Issue by ChillSheep** [LimerBoy/Adamantium-Thief#11]
Hi, could you try fixing the AES-GCM errors? There are a lot of them, not only in passwords but in cookies too

**Comment by LimerBoy** [comment]
Hi, try downloading the latest version, I fixed a few errors there.

**Comment by ChillSheep** [comment]
> Hi, try downloading the latest version, I fixed a few errors there.
It's still here
On my other pc always the password gives "failed (AES-GCM)" but the username works perfectly

**Comment by ChillSheep** [comment]
It was my other PC missing sodium libs, I heavily modified your code to work remotely and I deleted the checkdlls function by mistake, SOLVED!
