### ISSUE TITLE
Can we compile it in one executable?

### ISSUE THREAD

**Issue by davidfarah2003** [LimerBoy/Adamantium-Thief#12]
The dlls are annoying to work with

**Comment by LimerBoy** [comment]
You can do dynamic dll loading. so that they download from my github

**Comment by ChillSheep** [comment]
You can also use Costura.Fody, just use nuget and type this "Install-Package Costura.Fody -Version 4.1.0"

**Comment by 0xPh0enix** [comment]
You can use ilmerge.
