### ISSUE TITLE
mozilla support ?

### ISSUE THREAD

**Issue by lynaventura** [LimerBoy/Adamantium-Thief#15]
hi, first thank you for this very interresting and useful piece of code.
Are you intending to add support for mozilla new decryption in the future ?

**Comment by LimerBoy** [comment]
No

**Comment by lynaventura** [comment]
do you have a link that explains the new mozilla encryption please ?

**Comment by LimerBoy** [comment]
> do you have a link that explains the new mozilla encryption please ?

lol, you can just copy: 'logins.json' and 'key4.db' from Mozilla directory and paste to you Mozilla dir.
and in settings >> view logins

**Comment by LimerBoy** [comment]
https://github.com/LimerBoy/FireFox-Thief
